# ---------------------- AMCL 參數 ----------------------
amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    laser_z_hit: 0.5
    laser_z_rand: 0.5
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2

# ------------------- Planner Server 參數 -------------------
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      allow_unknown: true

# ------------------ Controller Server 參數 ------------------
controller_server:
  ros__parameters:
    controller_plugins: ["DWBLocalPlanner"]
    DWBLocalPlanner:
      plugin: "dwb_core::DWBLocalPlanner"
      critics:
        - name: "GoalAlign"
          plugin: "dwb_critics::GoalAlign"
        - name: "Oscillation"
          plugin: "dwb_critics::Oscillation"
        - name: "PathAlign"
          plugin: "dwb_critics::PathAlign"
        - name: "GoalDist"
          plugin: "dwb_critics::GoalDist"
      max_vel_x: 0.3
      min_vel_x: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      acc_lim_x: 1.0
      acc_lim_theta: 1.0
      decel_lim_x: -1.0
      decel_lim_theta: -1.0


# ------------------- BT Navigator 參數 -------------------
bt_navigator:
  ros__parameters:
    use_sim_time: false
    autostart: true
    plugin_lib_names:
      - "nav2_compute_path_to_pose_action_bt_node"
      - "nav2_follow_path_action_bt_node"
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

# --------------- Lifecycle Manager 參數 ---------------
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - amcl
      - planner_server
      - controller_server
      - bt_navigator
